name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit
  - cudnn
  - cupti
  - pip
  - pip:
    - cellpose
    - deepcell
    - ipython
    - keras
    - keras-preprocessing
    - lxml
    - matplotlib
    - networkx
    - numba
    - numpy
    - opencv-python-headless
    - pandas
    - pillow
    - scikit-image
    - scikit-learn
    - scipy
    - tensorflow
    - tensorflow-addons
    - tensorflow-estimator
    - tifffile
    - torch
