name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - ipython
  - lxml
  - manhole
  - matplotlib
  - pip
  - scikit-image
  - scikit-learn
  - scipy
  - tifffile
  - pip:
    - cellpose~=0.6.5
    - deepcell~=0.12.9
    - numba
